services:
  backend:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 4000:4000
    restart: always

volumes:
  postgres-data:
    driver: local
